version: 2.1

orbs:
  heroku: circleci/heroku@1.2

jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Testing app
          command: npm ci && npm run test

  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm i @nrwl/nx-cloud
      - run: npm run build

workflows:
  test-build-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main
